<?php

$words = [
    'manzana' => ['fruta', 'roja', 'dulce', 'jugo', 'pastel'],
    'perro' => ['mascota', 'ladrar', 'cola', 'hueso', 'cachorro'],
    'auto' => ['vehículo', 'motor', 'conducir', 'carretera', 'ruedas'],
    'casa' => ['hogar', 'techo', 'puerta', 'jardín', 'ventana'],
    'libro' => ['leer', 'páginas', 'autor', 'biblioteca', 'cubierta'],
    'computadora' => ['tecnología', 'teclado', 'pantalla', 'software', 'internet'],
    'escuela' => ['educación', 'maestro', 'alumnos', 'aula', 'tarea'],
    'música' => ['melodía', 'canción', 'instrumento', 'notas', 'concierto'],
    'película' => ['film', 'director', 'actor', 'escena', 'cine'],
    'comida' => ['plato', 'cocina', 'restaurante', 'comer', 'receta'],
    'juego' => ['diversión', 'reglas', 'puntuación', 'entretenimiento', 'competencia'],
    'ciudad' => ['urbano', 'edificios', 'tráfico', 'horizonte', 'calle'],
    'agua' => ['líquido', 'beber', 'océano', 'río', 'mojado'],
    'montaña' => ['cima', 'senderismo', 'escalar', 'naturaleza', 'nieve'],
    'árbol' => ['hoja', 'rama', 'madera', 'bosque', 'crecer'],
    'planeta' => ['espacio', 'tierra', 'órbita', 'estrella', 'sistema'],
    'avión' => ['vuelo', 'alas', 'aeropuerto', 'piloto', 'viajar'],
    'tren' => ['vía', 'estación', 'vagón', 'locomotora', 'viaje'],
    'hotel' => ['habitación', 'estadía', 'vacaciones', 'recepción', 'cama'],
    'restaurante' => ['menú', 'comedor', 'mesero', 'cocina', 'mesa'],
    'jardín' => ['plantas', 'flores', 'suelo', 'luz', 'crecer'],
    'teléfono' => ['llamada', 'mensaje', 'pantalla', 'batería', 'altavoz'],
    'barco' => ['océano', 'vela', 'capitán', 'cubierta', 'carga'],
    'cámara' => ['foto', 'lente', 'flash', 'imagen', 'película'],
    'aeropuerto' => ['avión', 'terminal', 'vuelo', 'equipaje', 'seguridad'],
    'puente' => ['cruzar', 'río', 'arco', 'carretera', 'soporte'],
    'zoológico' => ['animales', 'exposición', 'cuidador', 'recinto', 'vida salvaje'],
    'bicicleta' => ['pedal', 'montar', 'ruedas', 'casco', 'manillar'],
    'fútbol' => ['equipo', 'gol', 'campo', 'puntuación', 'partido'],
    'guitarra' => ['cuerdas', 'música', 'tocar', 'acorde', 'instrumento'],
    'televisión' => ['pantalla', 'control remoto', 'canales', 'transmisión', 'programa'],
    'teclado' => ['escribir', 'teclas', 'computadora', 'letras', 'entrada'],
    'taza' => ['bebida', 'asa', 'cerámica', 'café', 'platillo'],
    'tren' => ['locomotora', 'vía', 'vagón', 'estación', 'viaje'],
    'cámara' => ['fotografía', 'lente', 'obturador', 'enfoque', 'imagen'],
    'sol' => ['luz', 'día', 'solar', 'calor', 'estrella'],
    'luna' => ['noche', 'órbita', 'cráter', 'fase', 'satélite'],
    'río' => ['agua', 'flujo', 'banco', 'arroyo', 'corriente'],
    'playa' => ['arena', 'mar', 'sol', 'olas', 'orilla'],
    'ordenador' => ['tecnología', 'ratón', 'pantalla', 'teclado', 'programa'],
    'libro' => ['biblioteca', 'leer', 'autor', 'páginas', 'novela'],
    'café' => ['granos', 'infusión', 'taza', 'cafeína', 'mañana'],
    'perro' => ['ladrar', 'mascota', 'cola', 'correa', 'cachorro'],
    'gato' => ['maullar', 'mascota', 'pelaje', 'patas', 'gatito'],
    'pez' => ['agua', 'nadar', 'escamas', 'acuario', 'branquias'],
    'bicicleta' => ['pedal', 'ruedas', 'manillar', 'casco', 'montar'],
    'ciudad' => ['urbana', 'edificios', 'calles', 'tráfico', 'horizonte'],
    'calle' => ['camino', 'acera', 'coches', 'tráfico', 'cruce'],
    'mercado' => ['compras', 'productos', 'vendedores', 'precios', 'comida'],
];

?>
